#!/bin/bash 
#####################################################################
# Author: Christoph Weniger <christoph.weniger@gmail.com>
# Date: 25 Nov 2012
# Brief: Quick and dirty patch to turn DarkSUSY into a shared object
#
# Usage:
#  copy make_so_darksusy into darksusy root folder
#  run ./configure (or ./conf.gfortran etc)
#  run ./make_so_darksusy (runs make)
#
# Note: 
#  - After make_so_darksusy libdarksusy.so can be found under lib
#  - dsgalprop and galprop are excluded from the build (otherwise
#    there are remaining undefined references)
#  - DS makefiles do not explicitly generate position independent
#    code right now. In case of problems when generating the shared 
#    object, adding -fPIC to the compiler flags via the ./configure
#    script might be a solution.
#  - The patch works for me with GCC 4.5 and DarkSUSY 5.0.6
#####################################################################

# We are in darksusy root
DS_ROOT=$PWD

# Bad references (only subset related to isajet is relevant below)
BAD_REFS=$'RANF\nGGGXXX\nVXXXXX\nFTGIPR\nFFOPENTEST\nTIMEST\nFFRPRT\nRANFMT\nSSID\nJGGXXX\nFVIXXX\nFTGKYE\nRHO_DARKSUSY\nSORTTF\nFFGKY\nJIOXXX\nFFCLOS\nCOUP2X\nFTGPVE\nFTOPEN\nIOVXXX\nCOUP3X\nISALHE\nFFGPV\nFTCLOS\nFFUKY\nPDFSET\nFFCRIM\nPFTOPDG\nDATIME\nFFINIT\nFFPPR\nTIMEX\nFVOXXX\nOXXXXX\nGETPAS\nCOUP1X\nIXXXXX\nCOUP4X\nWHIGGS\nZJJ4\nTWOJET\nWPAIR\nPRTLIM\nFTGIPR\nFFOPENTEST\nFFRPRT\nMGINIT\nZJJ0\nFTGKYE\nTIMER\nZJJ3\nRHO_DARKSUSY\nFFGKY\nHEVOLV\nFFCLOS\nREADIN\nFTGPVE\nELCTRN\nFTOPEN\nZJJ6\nFFGPV\nZJJ1\nFTCLOS\nJETGEN\nFFUKY\nQCDINI\nZJJ7\nFFCRIM\nPTFUN\nFFINIT\nZJJ2\nQCDJET\nFFPPR\nZJJ5\nIDGEN\nSTRUC\nQFUNC\nDRLLYN\nEVOL07\nSIGSEE\nSIGEE\nRDBEG\nSETDKY\nSSFEL'

# Clean up isajet files
# (remove problematic object files from isajet makefile)
cd $DS_ROOT/contrib/isajet779-for-darksusy
BAD_FILES=`grep -l "$BAD_REFS" *.f` # collect files mentioning BAD_REFS
for FILE in $BAD_FILES
do
  FILE=${FILE/.f/.o}
  if [[ $FILE != "aldata.o"  ]]; then # aldata.o is special, don't touch it
    echo $FILE
    sed -e "s/${FILE}//" makefile > makefile.out
    mv makefile.out makefile
  fi
done

# Remove Galprop from darksusy
# (patch for root makefile)
cd $DS_ROOT
patch -N makefile $BASH_SOURCE

# Make darksusy
rm -f $DS_ROOT/lib/*.so # make does not like *.so files under lib
make

# And finally ...drum roll... generate libdarksusy.so 
cd $DS_ROOT/lib
mkdir tmp_so
cd tmp_so
ar x ../libdarksusy.a
gcc -shared -Wl,-soname,libdarksusy.so -o ../libdarksusy.so *.o
cd ../
rm -rf tmp_so
exit

# The rest is patch information for the root makefile
72c72
< all : feynhiggs higgsbounds darksusy libisajet galprop mains_if_loc
---
> all : feynhiggs higgsbounds darksusy libisajet mains_if_loc
76c76
< darksusy : darksusy_lib dsgalprop inst_tab_if_loc
---
> darksusy : darksusy_lib inst_tab_if_loc
