//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Automatically generated template             
///  specialisations for module functors, for     
///  the full GAMBIT executable.                  
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///                                               
///  The content is harvested from:               
///   - rollcall headers in module_rollcall.hpp   
///   - types registered in types_rollcall.hpp    
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 10:16AM on January 10, 2018
///                                               
///  *********************************************
                                                  
#ifndef __module_functor_types_hpp__              
#define __moduel_functor_types_hpp__              
                                                  
#include "gambit/Elements/types_rollcall.hpp"   
#include "gambit/Elements/functor_definitions.hpp"
                                                  
namespace Gambit                                  
{                                                 
  template class module_functor<ColliderBit::AnalysisNumbers>;
  template class module_functor<fh_HiggsProd>;
  template class module_functor<DarkBit::SimYieldTable>;
  template class module_functor<int>;
  template class module_functor<float>;
  template class module_functor<DarkBit::nuyield_info>;
  template class module_functor<map_int_triplet_dbl>;
  template class module_functor<hb_ModelParameters>;
  template class module_functor<const SubSpectrum*>;
  template class module_functor<std::vector<std::string>>;
  template class module_functor<fh_HiggsMassObs>;
  template class module_functor<fh_FlavourObs>;
  template class module_functor<std::vector<double>>;
  template class module_functor<SLHAstruct >;
  template class module_functor<daFunk::Funk>;
  template class module_functor<map_str_dbl>;
  template class module_functor<parameters>;
  template class module_functor<ColliderBit::SpecializablePythia>;
  template class module_functor<DarkBit::stringFunkMap>;
  template class module_functor<HiggsCouplingsTable>;
  template class module_functor<DarkBit::RD_spectrum_type>;
  template class module_functor<Pythia8::Event>;
  template class module_functor<fh_PrecisionObs>;
  template class module_functor<dbl_dbl_bool>;
  template class module_functor<SMInputs>;
  template class module_functor<MString>;
  template class module_functor<fh_Couplings>;
  template class module_functor<HEPUtils::Event>;
  template class module_functor<DarkBit::TH_ProcessCatalog>;
  template class module_functor<DarkBit::simpleHistContainter>;
  template class module_functor<triplet<double>>;
  template class module_functor<DecayBit::mass_es_pseudonyms>;
  template class module_functor<ColliderBit::HEPUtilsAnalysisContainer>;
  template class module_functor<std::vector<float>>;
  template class module_functor<MBool>;
  template class module_functor<fptr_dd>;
  template class module_functor<ColliderBit::BuckFastSmearCMS>;
  template class module_functor<fptr>;
  template class module_functor<DarkBit::DecayChain::DecayTable>;
  template class module_functor<GalacticHaloProperties>;
  template class module_functor<DecayTable>;
  template class module_functor<DM_nucleon_couplings>;
  template class module_functor<double>;
  template class module_functor<LocalMaxwellianHalo>;
  template class module_functor<DarkBit::stringIntMap>;
  template class module_functor<Spectrum>;
  template class module_functor<FlavBit::predictions_measurements_covariances>;
  template class module_functor<DarkBit::nudata>;
  template class module_functor<DecayTable::Entry>;
  template class module_functor<ModelParameters>;
  template class module_functor<DarkBit::DecayChain::ChainContainer>;
  template class module_functor<ColliderBit::BuckFastSmearATLAS>;
  template class module_functor<Flav_KstarMuMu_obs>;
  template class module_functor<ColliderBit::BuckFastIdentity>;
  template class module_functor<fh_MSSMMassObs>;
}

#endif // defined __module_functor_types_hpp__
