//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Explicit functor template class              
///  instantiations needed by standalone program  
///  DarkBit_standalone_MSSM_all_backends.                          
///                                               
///  This file was automatically generated by     
///  standalone_facilitator.py. Do not modify.    
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 10:50PM on February 11, 2020
///                                               
///  *********************************************
                                                  
#include "gambit/Elements/functor_definitions.hpp"
#include "gambit/Elements/types_rollcall.hpp"   
#include "gambit/Backends/backend_functor_types.hpp"
                                                  
namespace Gambit                                  
{                                                 
  // Non-module types                             
  template class module_functor<void>;            
  template class module_functor<LocalMaxwellianHalo>;
  template class module_functor<fh_Couplings>;
  template class module_functor<fh_PrecisionObs>;
  template class module_functor<double>;
  template class module_functor<map_str_dbl>;
  template class module_functor<mass_es_pseudonyms>;
  template class module_functor<fptr>;
  template class module_functor<fptr_dd>;
  template class module_functor<SMInputs>;
  template class module_functor<ddpair>;
  template class module_functor<DecayTable::Entry>;
  template class module_functor<bool>;
  template class module_functor<std::vector<float>>;
  template class module_functor<ModelParameters>;
  template class module_functor<std::vector<std::vector<double>>>;
  template class module_functor<const SubSpectrum*>;
  template class module_functor<dbl_dbl_bool>;
  template class module_functor<SLHAstruct>;
  template class module_functor<daFunk::Funk>;
  template class module_functor<fh_HiggsMassObs>;
  template class module_functor<DecayTable>;
  template class module_functor<GalacticHaloProperties>;
  template class module_functor<parameters>;
  template class module_functor<int>;
  template class module_functor<fh_MSSMMassObs>;
  template class module_functor<map_int_triplet_dbl>;
  template class module_functor<float>;
  template class module_functor<DM_nucleon_couplings>;
  template class module_functor<std::string>;
  template class module_functor<Spectrum>;
  template class module_functor<HiggsCouplingsTable>;
  template class module_functor<triplet<double>>;
  template class module_functor<map_intpair_dbl>;
  template class module_functor<unsigned>;
  template class module_functor<std::vector<double>>;
  template class module_functor<std::vector<std::string>>;
  template class module_functor<Eigen::Matrix3cd>;
  // Module types
  template class module_functor<DarkBit::stringFunkMap>;
  template class module_functor<DarkBit::SimYieldTable>;
  template class module_functor<DarkBit::RD_spectrum_type>;
  template class module_functor<DarkBit::TH_ProcessCatalog>;
  template class module_functor<DarkBit::simpleHistContainter>;
  template class module_functor<DarkBit::nuyield_info>;
  template class module_functor<DarkBit::stringIntMap>;
  template class module_functor<DarkBit::nudata>;
  template class module_functor<DarkBit::DecayChain::DecayTable>;
  template class module_functor<DarkBit::DecayChain::ChainContainer>;
}

// Define standalone versions of functor signal helpers (that do nothing)
namespace Gambit                                                      
{                                                                     
  namespace FunctorHelp                                               
  {                                                                   
    void check_for_shutdown_signal(module_functor_common&) {}         
    bool emergency_shutdown_begun() { return false; }                 
    void entering_multithreaded_region(module_functor_common&) {}     
    void leaving_multithreaded_region(module_functor_common&) {}      
  }                                                                   
}
