
BE_VARIABLE(pacodes_type, pacodes, "pacodes_", "cb_pacodes")
BE_VARIABLE(mspctm_type, mspctm, "mspctm_", "cb_mspctm")
BE_VARIABLE(widths_type, widths, "widths_", "cb_widths")
BE_VARIABLE(intdof_type, intdof, "intdof_", "cb_intdof")
BE_VARIABLE(vrtxs_type, vrtxs, "vrtxs_", "cb_vrtxs")
BE_VARIABLE(smruseful_type, smruseful, "smruseful_", "cb_smruseful")
BE_VARIABLE(smcuseful_type, smcuseful, "smcuseful_", "cb_smcuseful")
BE_VARIABLE(couplingconstants_type, couplingconstants, "couplingconstants_", "cb_couplingconstants")
BE_VARIABLE(sckm_type, sckm, "sckm_", "cb_sckm")
BE_VARIABLE(mixing_type, mixing, "mixing_", "cb_mixing")
BE_VARIABLE(mssmtype_type, mssmtype, "mssmtype_", "cb_mssmtype")
BE_VARIABLE(mssmpar_type, mssmpar, "mssmpar_", "cb_mssmpar")
BE_VARIABLE(mssmswitch_type, mssmswitch, "mssmswitch_", "cb_mssmswitch")
BE_VARIABLE(sfermionmass_type, sfermionmass, "sfermionmass_", "cb_sfermionmass")
BE_VARIABLE(mssmwidths_type, mssmwidths, "mssmwidths_", "cb_mssmwidths")
BE_VARIABLE(mssmmixing_type, mssmmixing, "mssmmixing_", "cb_mssmmixing")
