#!/bin/bash 

MICROPATH=/home/weniger/Downloads/micromegas_3.5.5/

cd MSSM
gcc  -shared -o ../micromegas.so main.c lib/aLib.a ../sources/micromegas.a $MICROPATH/CalcHEP_src/lib/dynamic_me.a ../sources/micromegas.a work/work_aux.a lib/aLib.a   $MICROPATH/CalcHEP_src/lib/sqme_aux.so $MICROPATH/CalcHEP_src/lib/libSLHAplus.a ../CalcHEP_src/lib/num_c.a ../CalcHEP_src/lib/ntools.a   ../CalcHEP_src/lib/serv.a -lX11 -rdynamic -ldl -lm
