#!/bin/bash 
#####################################################################
# Author: Nazila Mahmoudi  <nazila.mahmoudi@cern.ch>
# Date: 10 Jul 2013
# Brief: Quick and dirty patch to turn SuperIso into a shared object
#	 Based on Christoph Weniger script for DarkSusy
#
# Usage:
#  copy make_so_superiso into superiso root folder
#  configure the Makefile
#  run ./make_so_superiso (runs make)
#
# Note: after make_so_superiso libsuperiso.so can be found under src
#####################################################################

# We are in SuperIso root
SI_ROOT=$PWD

# Make SuperIso after adding -fPIC to the CFLAGS
rm -f $SI_ROOT/src/*.so # make does not like *.so files under src

make
cd $SI_ROOT/src/
make distclean
sed -i 's/CFLAGS =/CFLAGS = -lm -fPIC/g' FlagsForMake
make
sed -i 's/CFLAGS = -lm -fPIC/CFLAGS =/g' FlagsForMake

# And finally ...drum roll... generate libsuperiso.so 
mkdir tmp_so
cd tmp_so
ar x ../libisospin.a
gcc -shared -Wl,libsuperiso.so -o ../libsuperiso.so *.o -lm
cd ../
rm -rf tmp_so
exit
